blog/apps/post/urls.py
from django.urls import path
import apps.post.views as views

app_name = 'post'

urlpatterns = [
    path('posts/', views.PostListView.as_view(), name="post_list"),
    path('posts/create', views.PostCreateView.as_view(), name="post_create"),
    path('posts/<slug:slug>/', views.PostDetailView.as_view(), name='post_detail'),
    path('posts/<slug:slug>/update', views.PostDetailView.as_view(), name='post_update'),
    path('posts/<slug:slug>/delete', views.PostDetailView.as_view(), name='post_delete'),
    
]
    
#En este caso, se han definido las siguientes URLs:
#post_list: URL para listar los posts.
#post_create: URL para crear un nuevo post.
#post_detail: URL para ver un post en detalle.
#post_update: URL para actualizar un post.
#post_delete: URL para eliminar un post.

blog/apps/user/urls.py
# blog/apps/user/urls.py
from django.urls import path
import apps.user.views as views

app_name = 'user'

urlpatterns = [
    path('user/profile/', views.UserProfileView.as_view(), name='user_profile'),
    path('auth/register/', views.RegisterView.as_view(), name='auth_register'),
    path('auth/login/', views.LoginView.as_view(), name='auth_login'),
    path('auth/logout/', views.LogoutView.as_view(), name='auth_logout'),
]

blog/blog/urls.py
"""
URL configuration for blog project.

The urlpatterns list routes URLs to views. For more information please see:
https://docs.djangoproject.com/en/5.1/topics/http/urls/
Examples:
Function views
    
Add an import:  from my_app import views
Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    
Add an import:  from other_app.views import Home
Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    
Import the include() function: from django.urls import include, path
Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from blog.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='home'),
    path('', include('apps.user.urls')),
    path('', include('apps.post.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/templates/components/ui/navbar.html
<nav>
    <ul class="flex gap-4">
        <li><a href="{% url 'home' %}">Inicio</a></li>
        <li>
            <a href="{% url 'post:post_detail' slug='el-inicio-de-la-ia' %}"
                >Ver Post</a
            >
        </li>
        <li><a href="{% url 'user:user_profile' %}">Perfil</a></li>
        <li><a href="{% url 'user:auth_login' %}">Iniciar sesión</a></li>
        <li><a href="{% url 'user:auth_register' %}">Registrarse</a></li>
    </ul>
</nav>
       
<nav>
    <ul class="flex gap-4">
        <li><a href="{% url 'home' %}">Inicio</a></li>
        {% if user.is_authenticated %}
            <!-- Mostrar opciones si el usuario está autenticado -->
            <li><a href="{% url 'user:user_profile' %}">Perfil</a></li>
            <li>
                <form method="POST" action="{% url 'user:auth_logout' %}">
                    {% csrf_token %}
                    <button type="submit">Cerrar sesión</button>
                </form>
            </li>
        {% else %}
            <!-- Mostrar opciones si el usuario NO está autenticado -->
            <li><a href="{% url 'user:auth_login' %}">Iniciar sesión</a></li>
            <li><a href="{% url 'user:auth_register' %}">Registrarse</a></li>
        {% endif %}
    </ul>
</nav>

<nav>
    <ul class="flex gap-4">
        {% if user.is_authenticated %}
            {% if user.is_collaborator %}
                <li><a href="{% url 'post:post_create' %}">Publicar</a></li>
            {% endif %}
            <li><a href="{% url 'user:user_profile' %}">Perfil</a></li>
            <li>
                <form method="post" action="{% url 'user:auth_logout' %}">
                    {% csrf_token %}
                    <button type="submit">Cerrar sesión</button>
                </form>
            </li>
        {% else %}
            <li><a href="{% url 'user:auth_login' %}">Iniciar sesión</a></li>
            <li><a href="{% url 'user:auth_register' %}">Registrarse</a></li>
        {% endif %}
    </ul>
</nav>